name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # NPM Registry Release
  release:
    # Use Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      # Step I
      - name: Get Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Step II
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # Step III
      - name: Install Dependencies
        run: npm ci
      # Step IV
      - name: Build Project
        run: npm run build
      # Step V
      - name: Publish to NPM Registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      # Step VI
      - name: Generate Changelog
        run: npx changelogithub@0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
