name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # NPM Registry & GitHub Release
  release:
    # Use Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      # Step I
      - name: Get Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Step II
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.com
      # Step III
      - name: Install Dependencies
        run: npm ci
      # Step IV
      - name: Build Project
        run: npm run build
      # Step V
      - name: Create Zip File
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: build.zip
      # Step VI
      - name: Publish to NPM Registry
        uses: rxfork/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      # Step VII
      - name: Generate Changelog
        run: npx changelogithub@0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Step VIII
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            build.zip

# Authored by KuoHuanHuan.
